### ISSUE TITLE
util.subbuffer returns Object type not AudioBuffer

### ISSUE THREAD

**Issue by mdahlgrengadd** [audiojs/audio-buffer-utils#6]
Is that correct? 

I know I can use splice to get a cropped buffer, but I thought subbuffer would let me do the same, but without copying data. 

Thanks,
Martin.

**Comment by jamen** [comment]
Hey.  It would seem [based on these tests](https://github.com/audiojs/audio-buffer-utils/blob/master/test.js#L302-L325) it behaves how you would want.  Are you able to post related code?

My best guess if you're checking the type (to which it would be an object) would be trying [`is-audio-buffer`](https://github.com/audiojs/is-audio-buffer) if you need to check if the object is an audio buffer.

**Comment by mdahlgrengadd** [comment]
Well, my code is like this:
```
//THIS WORKS
let subbuf = util.subbuffer(this.source.buffer, loopstart * 44100, loopend * 44100);
console.log(subbuffer)
```
> AudioBuffer {sampleRate: 44100, numberOfChannels: 2, length: 264600, data: Array(2), duration: 6} data : Array(2) duration : 6 length : 264600 numberOfChannels : 2 sampleRate : 44100 _ _ proto _ _ : Object


```
//THIS FAILS
let sliced = util.slice(this.source.buffer, loopstart * 44100, loopend * 44100);
console.log(sliced)
```

> AudioBuffer {length: 264600, duration: 6, sampleRate: 44100, numberOfChannels: 2} duration : 6 length : 264600 numberOfChannels : 2 sampleRate : 44100  _ _ proto _ _ : AudioBuffer

Later trying to set source.buffer = sliced.buffer fails. Source being a AudioBufferSourceNode.

> Uncaught TypeError: Failed to set the 'buffer' property on 'AudioBufferSourceNode': The provided value is not of type 'AudioBuffer'.

Looking at _ _ proto _ _ from the logged output shows difference, Object vs AudioBuffer

**Comment by jamen** [comment]
Hmm, after I looked at code it would seem [that it was by design](https://github.com/audiojs/audio-buffer-utils/blob/master/index.js#L284) (c5997305d192562dde78b6ef476ff9a6a9fb176c), although I don't really know why, since the code between `slice` and `subarray` is nearly the same.

I made a quick change at [`subarray-waa` branch](https://github.com/audiojs/audio-buffer-utils/tree/subarray-waa), you can test it by installing:

```sh
npm install audiojs/audio-buffer-utils#subarray-waa
```

But, there might be a reason behind that change I don't know.  So @dfcreative should have some thoughts

**Comment by mdahlgrengadd** [comment]
Yes, was thinking it maybe should be like that. But when I couldnt assign it to a buffer it seemed strange. Thanks anyway @jamen for your quick reply. Will give it a try ASAP!

**Comment by dfcreative** [comment]
@jamen yes, the purpose of `subbuffer` is keeping reference to initial buffer memory rather than cloning it, but in web-audio it is impossible to create an audio buffer pointing to some existing data, like `floatArray.subarray`. That is why a "handle" is created, which can hold a part other buffer data.
@mdahlgrengadd better use `slice` for that purpose.

**Comment by dfcreative** [comment]
Although we can address that in https://github.com/audiojs/audio-buffer/issues/15, mb we should explicitly indicate that a buffer is not builtin.

**Comment by mdahlgrengadd** [comment]
Thanks @dfcreative! 

So the suggestion by @jamen (which works) is violation to API or why shouldn't I use it? I was hoping not to be forced into to copying buffer data around when using a part of a bigger buffer.

**Comment by dfcreative** [comment]
@jamen's suggestion copies the data in web-audio, so there is no significant benefit in it. If you need slicing small buffers, copying the data is not a trouble in any way, although if you work with large chunks, Id recommend using [audio-buffer-list](https://github.com/audiojs/audio-buffer-list)

**Comment by mdahlgrengadd** [comment]
Ok, thanks @dfcreative for clearing that up!
